# Generated by Django 5.2.7 on 2025-10-25 10:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0003_emailverification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nama Kecamatan"
                    ),
                ),
                (
                    "reg_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimasi 2-3 hari kerja",
                        max_digits=10,
                        verbose_name="Tarif Reguler (Rp)",
                    ),
                ),
                (
                    "exp_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimasi 1 hari kerja",
                        max_digits=10,
                        verbose_name="Tarif Express (Rp)",
                    ),
                ),
                (
                    "eta_reg",
                    models.CharField(
                        default="2-3 hari kerja",
                        max_length=50,
                        verbose_name="ETA Reguler",
                    ),
                ),
                (
                    "eta_exp",
                    models.CharField(
                        default="1 hari kerja",
                        max_length=50,
                        verbose_name="ETA Express",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kecamatan",
                "verbose_name_plural": "Kecamatan",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="shipping_di_is_acti_6191cc_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nama Penerima"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telepon")),
                ("street", models.TextField(verbose_name="Alamat")),
                (
                    "district_name",
                    models.CharField(max_length=100, verbose_name="Kecamatan"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Kode Pos"),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[("REG", "Reguler"), ("EXP", "Express")],
                        max_length=3,
                        verbose_name="Layanan Pengiriman",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Biaya Pengiriman"
                    ),
                ),
                (
                    "eta",
                    models.CharField(max_length=50, verbose_name="Estimasi Pengiriman"),
                ),
                (
                    "tracking_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Nomor Resi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="core.order",
                        verbose_name="Pesanan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pengiriman",
                "verbose_name_plural": "Pengiriman",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nama Lengkap"),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Nomor telepon harus berformat Indonesia (contoh: 08123456789 atau +628123456789)",
                                regex="^(\\+62|62|0)[0-9]{9,12}$",
                            )
                        ],
                        verbose_name="Nomor Telepon",
                    ),
                ),
                ("street", models.TextField(verbose_name="Alamat/Jalan")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Kode Pos"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Alamat Utama"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengguna",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="shipping.district",
                        verbose_name="Kecamatan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alamat",
                "verbose_name_plural": "Alamat",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_default"],
                        name="shipping_ad_user_id_d3e524_idx",
                    )
                ],
            },
        ),
    ]
