# Generated by Django 5.2.7 on 2025-10-25 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="address_line",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Alamat/Jalan"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="city_name",
            field=models.CharField(
                blank=True,
                help_text="ex: Makassar",
                max_length=120,
                verbose_name="Kota",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="destination_subdistrict_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID kecamatan tujuan (RajaOngkir).",
                null=True,
                verbose_name="ID Kecamatan Tujuan",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="is_primary",
            field=models.BooleanField(default=True, verbose_name="Alamat Primary"),
        ),
        migrations.AddField(
            model_name="address",
            name="province_name",
            field=models.CharField(
                blank=True,
                help_text="Set 'Sulawesi Selatan' saat simpan",
                max_length=120,
                verbose_name="Provinsi",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="subdistrict_name",
            field=models.CharField(
                blank=True,
                help_text="ex: Panakkukang",
                max_length=120,
                verbose_name="Kecamatan",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy field - gunakan destination_subdistrict_id untuk RajaOngkir",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.district",
                verbose_name="Kecamatan (Lokal)",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="full_name",
            field=models.CharField(max_length=120, verbose_name="Nama Lengkap"),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                max_length=30,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Nomor telepon harus berformat Indonesia (contoh: 08123456789 atau +628123456789)",
                        regex="^(\\+62|62|0)[0-9]{9,12}$",
                    )
                ],
                verbose_name="Nomor Telepon",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(blank=True, max_length=10, verbose_name="Kode Pos"),
        ),
        migrations.AlterField(
            model_name="address",
            name="street",
            field=models.TextField(blank=True, verbose_name="Alamat/Jalan (Legacy)"),
        ),
    ]
