# Generated by Django 5.2.7 on 2025-10-22 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Keranjang",
                "verbose_name_plural": "Keranjang",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nomor Pesanan"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Menunggu Pembayaran"),
                            ("processing", "Diproses"),
                            ("shipped", "Dikirim"),
                            ("delivered", "Selesai"),
                            ("cancelled", "Dibatalkan"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="Nama Lengkap"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Nomor Telepon"),
                ),
                ("address", models.TextField(verbose_name="Alamat")),
                ("city", models.CharField(max_length=100, verbose_name="Kota")),
                (
                    "postal_code",
                    models.CharField(max_length=10, verbose_name="Kode Pos"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "shipping_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Ongkir",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Catatan")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesanan",
                "verbose_name_plural": "Pesanan",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=200, verbose_name="Nama Produk"),
                ),
                (
                    "product_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Harga Produk"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(verbose_name="Jumlah")),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.order",
                        verbose_name="Pesanan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalog.product",
                        verbose_name="Produk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Pesanan",
                "verbose_name_plural": "Item Pesanan",
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Nomor Telepon"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Alamat")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="Kota"),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Kode Pos"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil Pengguna",
                "verbose_name_plural": "Profil Pengguna",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="Jumlah"),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.cart",
                        verbose_name="Keranjang",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalog.product",
                        verbose_name="Produk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Keranjang",
                "verbose_name_plural": "Item Keranjang",
                "unique_together": {("cart", "product")},
            },
        ),
    ]
