# Generated by Django 5.2.7 on 2025-10-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_emailverification"),
        ("shipping", "0002_address_address_line_address_city_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="selected_courier",
            field=models.CharField(
                blank=True,
                help_text="jne/jnt/sicepat/tiki/pos/anteraja",
                max_length=20,
                verbose_name="Kurir Dipilih",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="selected_service_name",
            field=models.CharField(
                blank=True,
                help_text="REG/YES/OKE/etc",
                max_length=80,
                verbose_name="Layanan Kurir",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                help_text="Alamat tujuan pengiriman",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shipping.address",
                verbose_name="Alamat Pengiriman",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_weight_gram",
            field=models.PositiveIntegerField(
                default=1000,
                help_text="Total berat pesanan dalam gram",
                verbose_name="Total Berat (gram)",
            ),
        ),
    ]
