# Generated by Django 5.2.8 on 2025-11-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_paymentmethod"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        help_text="Midtrans transaction ID / order_id",
                        max_length=100,
                        unique=True,
                        verbose_name="Transaction ID",
                    ),
                ),
                (
                    "snap_token",
                    models.CharField(
                        blank=True,
                        help_text="Token untuk Snap popup",
                        max_length=255,
                        verbose_name="Snap Token",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        help_text="credit_card, bank_transfer, gopay, dll",
                        max_length=50,
                        verbose_name="Tipe Pembayaran",
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Jumlah Pembayaran",
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("capture", "Capture"),
                            ("settlement", "Settlement"),
                            ("deny", "Deny"),
                            ("cancel", "Cancel"),
                            ("expire", "Expire"),
                            ("failure", "Failure"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status Transaksi",
                    ),
                ),
                (
                    "fraud_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accept", "Accept"),
                            ("challenge", "Challenge"),
                            ("deny", "Deny"),
                        ],
                        max_length=20,
                        verbose_name="Status Fraud",
                    ),
                ),
                (
                    "status_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Status Code"
                    ),
                ),
                (
                    "signature_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Signature Key"
                    ),
                ),
                (
                    "response_midtrans",
                    models.JSONField(
                        blank=True,
                        help_text="Full response from Midtrans API",
                        null=True,
                        verbose_name="Response Midtrans",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diperbarui"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transaction",
                        to="core.order",
                        verbose_name="Pesanan",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.paymentmethod",
                        verbose_name="Metode Pembayaran",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaksi Pembayaran",
                "verbose_name_plural": "Transaksi Pembayaran",
                "ordering": ["-created_at"],
            },
        ),
    ]
