# Generated by Django 5.2.8 on 2025-11-06 15:18

from django.db import migrations


def create_midtrans_payment_method(apps, schema_editor):
    """Create Midtrans Snap payment method"""
    PaymentMethod = apps.get_model('core', 'PaymentMethod')

    # Check if Midtrans payment method already exists
    if not PaymentMethod.objects.filter(slug='midtrans-snap').exists():
        PaymentMethod.objects.create(
            name='Midtrans Snap',
            slug='midtrans-snap',
            tagline='Pembayaran Praktis & Aman',
            description='Bayar dengan berbagai metode: Kartu Kredit, Transfer Bank, E-Wallet (GoPay, ShopeePay), QRIS, dan lainnya.',
            additional_info='Anda akan diarahkan ke halaman pembayaran Midtrans yang aman setelah klik Checkout.',
            button_label='Bayar Sekarang',
            is_active=True,
            display_order=1,
        )


def remove_midtrans_payment_method(apps, schema_editor):
    """Remove Midtrans Snap payment method"""
    PaymentMethod = apps.get_model('core', 'PaymentMethod')
    PaymentMethod.objects.filter(slug='midtrans-snap').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_paymenttransaction"),
    ]

    operations = [
        migrations.RunPython(create_midtrans_payment_method, remove_midtrans_payment_method),
    ]
