# Generated by Django 5.2.7 on 2025-11-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_midtrans_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Pembayaran'), ('paid', 'Dibayar'), ('processing', 'Diproses'), ('shipped', 'Dikirim'), ('delivered', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
