# Generated by Django 5.2.7 on 2025-10-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nama Kategori"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(blank=True, verbose_name="Deskripsi")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kategori",
                "verbose_name_plural": "Kategori",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nama Produk")),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("description", models.TextField(verbose_name="Deskripsi")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Harga"
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Harga Diskon",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="products/",
                        verbose_name="Gambar",
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0, verbose_name="Stok")),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="Tersedia"),
                ),
                (
                    "weight_gram",
                    models.PositiveIntegerField(
                        default=1000,
                        help_text="Berat per unit (gram). Minimal 1000 gram untuk ongkir.",
                        verbose_name="Berat (gram)",
                    ),
                ),
                (
                    "length_cm",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Panjang (cm) – opsional",
                        verbose_name="Panjang (cm)",
                    ),
                ),
                (
                    "width_cm",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Lebar (cm) – opsional",
                        verbose_name="Lebar (cm)",
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Tinggi (cm) – opsional",
                        verbose_name="Tinggi (cm)",
                    ),
                ),
                (
                    "is_fragile",
                    models.BooleanField(
                        default=False,
                        help_text="Mudah pecah (opsional)",
                        verbose_name="Mudah Pecah",
                    ),
                ),
                (
                    "is_perishable",
                    models.BooleanField(
                        default=False,
                        help_text="Mudah rusak (opsional)",
                        verbose_name="Mudah Rusak",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Kategori",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produk",
                "verbose_name_plural": "Produk",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        choices=[
                            (1, "1 Star"),
                            (2, "2 Stars"),
                            (3, "3 Stars"),
                            (4, "4 Stars"),
                            (5, "5 Stars"),
                        ],
                        verbose_name="Rating",
                    ),
                ),
                ("review", models.TextField(verbose_name="Ulasan")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="testimonials/",
                        verbose_name="Foto",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_approved",
                    models.BooleanField(default=True, verbose_name="Disetujui"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to="catalog.product",
                        verbose_name="Produk",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="testimonials",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pengguna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Testimoni",
                "verbose_name_plural": "Testimoni",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["slug"], name="catalog_pro_slug_2b1eb6_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["-created_at"], name="catalog_pro_created_eee82f_idx"
            ),
        ),
    ]
