# Generated by Django 5.2.7 on 2025-01-01 00:00
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kode')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Nilai potongan dalam rupiah', max_digits=10, verbose_name='Nominal Diskon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Biarkan kosong jika tanpa batas waktu', null=True, verbose_name='Berlaku Sampai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kode Diskon',
                'verbose_name_plural': 'Kode Diskon',
                'ordering': ['-created_at'],
            },
        ),
    ]
