# Generated by Django 5.2.7 on 2025-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="height_cm",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Tinggi (cm) – opsional",
                verbose_name="Tinggi (cm)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_fragile",
            field=models.BooleanField(
                default=False,
                help_text="Mudah pecah (opsional)",
                verbose_name="Mudah Pecah",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_perishable",
            field=models.BooleanField(
                default=False,
                help_text="Mudah rusak (opsional)",
                verbose_name="Mudah Rusak",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="length_cm",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Panjang (cm) – opsional",
                verbose_name="Panjang (cm)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="weight_gram",
            field=models.PositiveIntegerField(
                default=1000,
                help_text="Berat per unit (gram). Minimal 1000 gram untuk ongkir.",
                verbose_name="Berat (gram)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="width_cm",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Lebar (cm) – opsional",
                verbose_name="Lebar (cm)",
            ),
        ),
    ]
