# Generated by Django 5.2.7 on 2025-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_carbohydrates"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Tampilkan produk ini sebagai produk unggulan di beranda",
                verbose_name="Favorit",
            ),
        ),
    ]
