# Generated by Django 5.2.7 on 2025-11-26 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_is_featured"),
        ("core", "0010_alter_order_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testimonial",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="testimonials",
                to="core.order",
                verbose_name="Pesanan",
            ),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order__isnull", False)),
                fields=("order", "product", "user"),
                name="unique_testimonial_per_order_product_user",
            ),
        ),
    ]
