# Generated by Django 5.2.7 on 2025-11-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_testimonial_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="flash_sale_duration_hours",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Durasi Flash Sale dalam jam (mis. 1, 3, 6)",
                verbose_name="Durasi (Jam)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="flash_sale_end",
            field=models.DateTimeField(
                blank=True,
                help_text="Diisi otomatis berdasarkan durasi",
                null=True,
                verbose_name="Berakhir Flash Sale",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="flash_sale_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Harga Flash Sale",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="flash_sale_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Mulai Flash Sale"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_flash_sale",
            field=models.BooleanField(
                default=False,
                help_text="Centang untuk menjadikan produk ini bagian dari Flash Sale",
                verbose_name="Aktifkan Flash Sale",
            ),
        ),
    ]
