# Generated by Django 5.2.7 on 2025-11-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_flash_sale_duration_hours_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nama")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=50, verbose_name="Nomor Telepon"),
                ),
                ("subject", models.CharField(max_length=150, verbose_name="Subjek")),
                ("message", models.TextField(verbose_name="Pesan")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Dikirim Pada"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pesan Kontak",
                "verbose_name_plural": "Pesan Kontak",
                "ordering": ["-created_at"],
            },
        ),
    ]
